services:
  spybot-web:
    build:
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=.buildx-cache/spybot-web
      cache_to:
        - type=local,dest=.buildx-cache/spybot-web,mode=max
    environment:
      SPRING_PROFILES_ACTIVE: ""
      #SPRING_PROFILES_ACTIVE: localdev
    volumes:
      - $PWD:/workspace
  caddy:
    ports:
      - "80:80"
#      - "443:443"
#      - "443:443/udp"
    volumes:
      - $PWD/infrastructure/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  #db:
    #ports:
    #  - "5432:5432"
