kotlin.code.style=official
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.jvmargs=-Xms256m -Xmx1024m -XX:MaxMetaspaceSize=2G -Dfile.encoding=UTF-8
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
springBootVersion=4.0.3
jteVersion=3.2.3
jooqVersion=3.20.6
testcontainersVersion=1.21.3
