package com.spybot.web.service.namegen

enum class Lang { DE, EN }

/**
 * A well-known person. [lang] drives how the name is transcribed (German rules vs. CMUdict);
 * [firstIpa]/[lastIpa] override that for names either source gets wrong. [region] is display only.
 */
data class FamousPerson(
    val firstName: String,
    val lastName: String,
    val category: String,
    val region: String,
    val lang: Lang,
    val firstIpa: String? = null,
    val lastIpa: String? = null,
)

/** A Counter-Strike term with its pronunciation; [display] is how it appears inside a generated name. */
data class SlangTerm(
    val word: String,
    val ipa: String,
    val display: String = word.replaceFirstChar { it.uppercase() },
)

/**
 * The two vocabularies the generator combines. Both are hand-maintained for now: add a person
 * or a term and the matcher decides on its own whether any pun falls out - there is no list of
 * finished names anywhere.
 */
object SeedData {
    private const val GERMAN = "German"
    private const val INTERNATIONAL = "International"

    private fun de(
        first: String,
        last: String,
        category: String,
        firstIpa: String? = null,
        lastIpa: String? = null,
    ) = FamousPerson(first, last, category, GERMAN, Lang.DE, firstIpa, lastIpa)

    private fun en(
        first: String,
        last: String,
        category: String,
        firstIpa: String? = null,
        lastIpa: String? = null,
    ) = FamousPerson(first, last, category, INTERNATIONAL, Lang.EN, firstIpa, lastIpa)

    val people: List<FamousPerson> =
        listOf(
            // ---- German ----
            de("Gregor", "Gysi", "Politician"),
            de("Harald", "Lesch", "TV personality"),
            de("Angela", "Merkel", "Politician", firstIpa = "aŋɡeːla"),
            de("Olaf", "Scholz", "Politician"),
            de("Markus", "Lanz", "TV personality"),
            de("Günther", "Jauch", "TV personality"),
            de("Thomas", "Gottschalk", "TV personality"),
            de("Dieter", "Bohlen", "TV personality"),
            de("Jan", "Böhmermann", "TV personality"),
            de("Klaas", "Heufer-Umlauf", "TV personality"),
            de("Joko", "Winterscheidt", "TV personality"),
            de("Anke", "Engelke", "Comedian"),
            de("Barbara", "Schöneberger", "TV personality"),
            de("Til", "Schweiger", "Actor"),
            de("Matthias", "Schweighöfer", "Actor"),
            de("Christian", "Lindner", "Politician"),
            de("Robert", "Habeck", "Politician"),
            de("Helmut", "Kohl", "Politician"),
            de("Willy", "Brandt", "Politician"),
            de("Karl", "Lauterbach", "Politician"),
            de("Sahra", "Wagenknecht", "Politician"),
            de("Hansi", "Flick", "Football coach"),
            de("Jürgen", "Klopp", "Football coach"),
            de("Oliver", "Kahn", "Footballer", firstIpa = "oːlivɐ"),
            de("Lukas", "Podolski", "Footballer"),
            de("Bastian", "Schweinsteiger", "Footballer"),
            de("Franz", "Beckenbauer", "Footballer"),
            de("Heidi", "Klum", "TV personality"),
            de("Elyas", "M'Barek", "Actor", firstIpa = "eːlias", lastIpa = "ɛmbaːʁɛk"),
            de("Hape", "Kerkeling", "Comedian"),
            de("Otto", "Waalkes", "Comedian"),
            de("Stefan", "Raab", "TV personality", firstIpa = "ʃtɛfan"),
            de("Horst", "Seehofer", "Politician"),
            de("Arnold", "Schwarzenegger", "Actor", lastIpa = "ʃvaɐtsənɛɡɐ"),
            de("Boris", "Becker", "Tennis player"),
            de("Steffi", "Graf", "Tennis player"),
            de("Helene", "Fischer", "Singer"),
            de("Frank", "Elstner", "TV personality"),
            de("Gerhard", "Schröder", "Politician"),
            de("Philipp", "Lahm", "Footballer"),
            de("Michael", "Schumacher", "Racing driver", firstIpa = "mɪçaɛl"),
            de("Toni", "Kroos", "Footballer"),
            de("Manuel", "Neuer", "Footballer"),
            de("Thomas", "Müller", "Footballer"),
            de("Nena", "Kerner", "Singer"),
            de("Udo", "Lindenberg", "Singer"),
            de("Herbert", "Grönemeyer", "Singer"),
            de("Mario", "Barth", "Comedian"),
            de("Bully", "Herbig", "Comedian", firstIpa = "bʊli"),
            de("Klaus", "Kinski", "Actor"),
            de("Hans", "Zimmer", "Composer"),
            de("Christoph", "Waltz", "Actor"),
            de("Daniel", "Brühl", "Actor"),
            // ---- International ----
            en("Harry", "Potter", "Fictional character"),
            en("Sean", "Connery", "Actor"),
            en("Henry", "Cavill", "Actor", lastIpa = "kævɪl"),
            en("Tom", "Hanks", "Actor"),
            en("Larry", "King", "TV personality"),
            en("Keanu", "Reeves", "Actor"),
            en("Dwayne", "Johnson", "Actor"),
            en("Emma", "Watson", "Actor"),
            en("Ryan", "Reynolds", "Actor"),
            en("Hugh", "Jackman", "Actor"),
            en("Morgan", "Freeman", "Actor"),
            en("Bruce", "Willis", "Actor"),
            en("Nicolas", "Cage", "Actor"),
            en("Brad", "Pitt", "Actor"),
            en("Matt", "Damon", "Actor"),
            en("Will", "Smith", "Actor"),
            en("Tom", "Cruise", "Actor"),
            en("Johnny", "Depp", "Actor"),
            en("Leonardo", "DiCaprio", "Actor"),
            en("Scarlett", "Johansson", "Actor"),
            en("Angelina", "Jolie", "Actor"),
            en("Meryl", "Streep", "Actor"),
            en("David", "Attenborough", "TV personality"),
            en("Barack", "Obama", "Politician"),
            en("Winston", "Churchill", "Politician"),
            en("Elon", "Musk", "Entrepreneur", firstIpa = "ilɑn"),
            en("Steve", "Jobs", "Entrepreneur"),
            en("Bill", "Gates", "Entrepreneur"),
            en("Jackie", "Chan", "Actor"),
            en("Chuck", "Norris", "Actor"),
            en("Samuel", "Jackson", "Actor"),
            en("Gordon", "Ramsay", "TV personality"),
            en("James", "Bond", "Fictional character"),
            en("Darth", "Vader", "Fictional character", firstIpa = "dɑɹθ"),
            en("Luke", "Skywalker", "Fictional character"),
            en("Frodo", "Baggins", "Fictional character", lastIpa = "bæɡɪnz"),
        )

    private fun t(
        word: String,
        ipa: String,
        display: String? = null,
    ) = if (display == null) SlangTerm(word, ipa) else SlangTerm(word, ipa, display)

    val slang: List<SlangTerm> =
        listOf(
            t("carry", "kæɹi"),
            t("clutch", "klʌtʃ"),
            t("ace", "eɪs"),
            t("whiff", "wɪf"),
            t("flash", "flæʃ"),
            t("flashbang", "flæʃbæŋ"),
            t("smoke", "smoʊk"),
            t("molly", "mɑli"),
            t("molotov", "mɑlətɔf"),
            t("nade", "neɪd"),
            t("frag", "fɹæɡ"),
            t("fragging", "fɹæɡɪŋ"),
            t("entry", "ɛntɹi"),
            t("trade", "tɹeɪd"),
            t("trader", "tɹeɪdɚ"),
            t("bait", "beɪt"),
            t("baiter", "beɪtɚ"),
            t("peek", "pik"),
            t("peeker", "pikɚ"),
            t("spray", "spɹeɪ"),
            t("tap", "tæp"),
            t("one-tap", "wʌntæp"),
            t("burst", "bɚst"),
            t("recoil", "ɹikɔɪl"),
            t("aim", "eɪm"),
            t("aimbot", "eɪmbɑt"),
            t("flick", "flɪk"),
            t("wallbang", "wɔlbæŋ"),
            t("wallhack", "wɔlhæk"),
            t("prefire", "pɹifaɪɚ"),
            t("rotate", "ɹoʊteɪt"),
            t("retake", "ɹiteɪk"),
            t("plant", "plænt"),
            t("defuse", "difjuz"),
            t("eco", "ikoʊ"),
            t("force", "fɔɹs"),
            t("save", "seɪv"),
            t("rush", "ɹʌʃ"),
            t("rusher", "ɹʌʃɚ"),
            t("stack", "stæk"),
            t("lurk", "lɚk"),
            t("lurker", "lɚkɚ"),
            t("rat", "ɹæt"),
            t("camp", "kæmp"),
            t("camper", "kæmpɚ"),
            t("spawn", "spɔn"),
            t("site", "saɪt"),
            t("awp", "ɔp", "AWP"),
            t("awper", "ɔpɚ", "AWPer"),
            t("scope", "skoʊp"),
            t("ping", "pɪŋ"),
            t("lag", "læɡ"),
            t("tilt", "tɪlt"),
            t("choke", "tʃoʊk"),
            t("throw", "θɹoʊ"),
            t("smurf", "smɚf"),
            t("noob", "nub"),
            t("rank", "ɹæŋk"),
            t("ranks", "ɹæŋks"),
            t("boost", "bust"),
            t("nuke", "nuk"),
            t("dust", "dʌst"),
            t("mirage", "mɪɹɑʒ"),
            t("inferno", "ɪnfɚnoʊ"),
            t("cache", "kæʃ"),
            t("vertigo", "vɚtɪɡoʊ"),
            t("overpass", "oʊvɚpæs"),
            t("train", "tɹeɪn"),
            t("easy", "izi"),
            t("rekt", "ɹɛkt"),
            t("headshot", "hɛdʃɑt"),
            t("deagle", "diɡəl"),
            t("strafe", "stɹeɪf"),
            t("bhop", "bihɑp"),
            t("drop", "dɹɑp"),
            t("blind", "blaɪnd"),
            t("wall", "wɔl"),
            t("clip", "klɪp"),
            t("kit", "kɪt"),
            t("bomb", "bɑm"),
            t("knife", "naɪf"),
            t("zeus", "zus"),
            t("glock", "ɡlɑk"),
            t("bunny", "bʌni"),
            t("cheater", "tʃitɚ"),
            t("hacker", "hækɚ"),
            t("toxic", "tɑksɪk"),
            t("kick", "kɪk"),
            t("mute", "mjut"),
            t("tick", "tɪk"),
            t("ninja", "nɪndʒə"),
            t("gg", "dʒidʒi", "GG"),
            t("flank", "flæŋk"),
            t("whiffer", "wɪfɚ"),
            t("vac", "væk", "VAC"),
            t("bot", "bɑt"),
            t("fake", "feɪk"),
            t("scout", "skaʊt"),
            t("silver", "sɪlvɚ"),
            t("global", "ɡloʊbəl"),
            t("elo", "iloʊ"),
            t("crouch", "kɹaʊtʃ"),
            t("dink", "dɪŋk"),
            t("spam", "spæm"),
        )
}
