# Generated by Django 4.1.3 on 2022-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSChannel',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'TSChannel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSID',
            fields=[
                ('ts_id', models.CharField(db_column='tsID', max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TSID',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'TSUser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSUserActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('end_time', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('joined', models.BooleanField(default=False)),
                ('disconnect_id', models.IntegerField(blank=True, db_column='discID', null=True)),
            ],
            options={
                'db_table': 'TSUserActivity',
                'managed': False,
            },
        ),
    ]
