# Generated by Django 4.2.15 on 2024-10-30 21:30

from django.db import migrations
import spybot.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("spybot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlink",
            name="code",
            field=spybot.models.Char32UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
