# Generated by Django 5.1.6 on 2025-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spybot", "0002_alter_loginlink_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tschannel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tsuseractivity",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
