# Generated by Django 4.1.3 on 2022-12-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0002_tsuser_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tsuseractivity',
            old_name='channel_id',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='tsuseractivity',
            old_name='tsuser_id',
            new_name='tsuser',
        ),
    ]
