# Generated by Django 5.1.6 on 2025-02-20 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spybot", "0002_alter_loginlink_code"),
    ]

    operations = []
