# Generated by Django 4.1.3 on 2022-12-13 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0003_rename_channel_id_tsuseractivity_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_hours', models.FloatField()),
            ],
            options={
                'db_table': 'HourlyActivity',
            },
        ),
    ]
