# Generated by Django 4.1.3 on 2022-12-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0004_hourlyactivity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hourlyactivity',
            index=models.Index(fields=['datetime'], name='HourlyActiv_datetim_96f0af_idx'),
        ),
    ]
