# Generated by Django 4.1.4 on 2022-12-30 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0006_tsuseractivity_tsuseractiv_startti_95ea75_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsuser',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='QueuedClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=128)),
                ('date', models.DateField(auto_now_add=True)),
                ('tsuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spybot.tsuser')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('USER_OF_WEEK', 'User of the week')], default='USER_OF_WEEK', max_length=64)),
                ('points', models.IntegerField()),
                ('tsuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spybot.tsuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='queuedclientmessage',
            constraint=models.UniqueConstraint(fields=('tsuser', 'type'), name='constraint_unique_type_user'),
        ),
    ]
