# Generated by Django 4.1.5 on 2023-01-16 20:53

from django.db import migrations
import spybot.models


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0009_newsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsuser',
            name='id',
            field=spybot.models.PositiveAutoField(primary_key=True, serialize=False),
        ),
    ]
