# Generated by Django 4.1.7 on 2023-07-02 14:30

from django.db import migrations, models
import django.db.models.deletion


def create_merged_users(apps, schema_editor):
    TSUser = apps.get_model("spybot", "TSUser")
    MergedUser = apps.get_model("spybot", "MergedUser")
    for user in TSUser.objects.all():
        merged = MergedUser(name=user.name)
        merged.save()
        user.merged_user = merged
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0011_alter_tsuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tsuser',
            name='merged_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spybot.mergeduser'),
        ),
        migrations.AddField(
            model_name='mergeduser',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tsuser',
            name='merged_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tsusers',
                                    to='spybot.mergeduser'),
        ),
        migrations.RunPython(create_merged_users)
    ]
