# Generated by Django 4.2.3 on 2023-07-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0013_migrate_old_newsevent_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeduser',
            name='steam_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='award',
            name='tsuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='spybot.tsuser'),
        ),
    ]
