# Generated by Django 4.2.3 on 2023-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0014_mergeduser_steam_id_alter_award_tsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergeduser',
            name='steam_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
