# Generated by Django 4.2.3 on 2023-07-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0016_steamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergeduser',
            name='steam_id',
        ),
    ]
