# Generated by Django 4.2.3 on 2023-07-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0017_remove_mergeduser_steam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamid',
            name='account_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
