# Generated by Django 4.2.3 on 2023-11-13 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0018_steamid_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='mergeduser',
            name='password',
            field=models.CharField(default='none', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LoginLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loginlinks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
