# Generated by Django 4.2.3 on 2024-01-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0019_mergeduser_last_login_mergeduser_password_loginlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL("UPDATE spybot_mergeduser SET is_superuser=true WHERE id=657;"),
        migrations.RunSQL("UPDATE spybot_mergeduser SET is_superuser=true WHERE id=641;"),
    ]
