# Generated by Django 4.2.3 on 2024-07-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spybot', '0021_userpasskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpasskey',
            name='token',
            field=models.CharField(max_length=1024),
        ),
    ]
