services:
  spybot-web:
    image: ghcr.io/smofladru/spybot2-web:${SPYBOT_IMAGE_TAG:-latest}
    init: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "8000:8000"
    depends_on:
      - db
    secrets:
      - db_password
  spybot-recorder:
    image: ghcr.io/smofladru/spybot2-recorder:${SPYBOT_IMAGE_TAG:-latest}
    init: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    depends_on:
      - db
    secrets:
      - db_password
  caddy:
    image: 'caddy:2.8-alpine'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "20001:20001"
    volumes:
      - $PWD/infrastructure/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  db:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - spybot_pg_data:/var/lib/postgresql/data
    secrets:
      - db_password
    ports:
      - "127.0.0.1:5432:5432"
volumes:
  caddy_data:
  caddy_config:
  spybot_pg_data:
secrets:
  db_password:
    file: secrets/db_password.txt
